import os
import sys
import subprocess
import tempfile
import ast
from dotenv import load_dotenv
from langchain_ollama import ChatOllama
from langchain_core.messages import HumanMessage, SystemMessage
from state import AgentState

load_dotenv()

# Specialized models via Ollama
coder_llm = ChatOllama(model="qwen2.5-coder:7b", temperature=0.1)
supervisor_llm = ChatOllama(model="llama3.2", temperature=0.0)

def is_executable_script(code_str: str) -> bool:
    """Checks if the code contains top-level executable blocks."""
    try:
        tree = ast.parse(code_str)
        for node in tree.body:
            if isinstance(node, (ast.Expr, ast.For, ast.While, ast.If, ast.With)):
                return True
        return False
    except:
        return False

# --- DEVELOPER NODE (WITH LOOP CONTROL) ---
def developer_node(state: AgentState) -> dict:
    """Specialized node to draft software logic and source code."""
    
    # CRITICAL FIX: Explicitly command the agent to REMOVE any intentional bugs during a fix phase
    is_fixing = bool(state.get("qc_report") or state.get("execution_output"))
    
    if is_fixing:
        system_prompt = (
            "You are an expert Senior Software Engineer. Your job is to FIX the code perfectly.\n"
            "CRITICAL: Do NOT include any intentional bugs, typos, or placeholders anymore. "
            "Fix the previously reported errors completely and output a 100% production-ready, working solution "
            "inside a standard python markdown block."
        )
    else:
        system_prompt = (
            "You are an expert Senior Software Engineer. Your job is to write code based on the user's request. "
            "Always output clean, commented, modular code inside a standard python markdown block."
        )
    
    filtered_messages = [SystemMessage(content=system_prompt)]
    
    # Pass the specific issue to focus on, hiding the confusing historical request to bug the code
    if state.get("execution_output"):
        filtered_messages.append(HumanMessage(content=f"Your previous code crashed during runtime:\n{state['execution_output']}"))
    elif state.get("qc_report"):
        filtered_messages.append(HumanMessage(content=f"Please fix the code according to this feedback:\n{state['qc_report']}"))
    else:
        filtered_messages.append(state["messages"][0]) # Fresh initial prompt
        
    response = coder_llm.invoke(filtered_messages)
    return {
        "messages": [response],
        "current_code": response.content,
        "next": "supervisor"
    }

# --- QC NODE ---
def qc_node(state: AgentState) -> dict:
    """Specialized node to run static analysis on developer output."""
    system_prompt = (
        "You are an elite Quality Control Engineer. Critique the code provided.\n"
        "Check for syntax errors, logical bugs, and missing imports.\n"
        "CRITICAL: You must explicitly end your response with either 'STATUS: PASSED' or 'STATUS: FAILED'."
    )
    
    code_to_test = state.get("current_code", "No code has been written yet.")
    messages = [SystemMessage(content=system_prompt), HumanMessage(content=f"Code:\n{code_to_test}")]
    
    response = coder_llm.invoke(messages)
    return {
        "messages": [response],
        "qc_report": response.content,
        "next": "supervisor"
    }

# --- SUPERVISOR NODE ---
def supervisor_node(state: AgentState) -> dict:
    """Orchestrator node ensuring workflow logic meets constraints."""
    has_code = bool(state.get("current_code"))
    has_qc = bool(state.get("qc_report"))
    has_run = bool(state.get("execution_output"))
    
    if not has_code:
        return {"next": "developer"}
        
    if has_code and not has_qc:
        return {"next": "qc"}
        
    # Read the text string directly to decide the next step
    raw_qc = state.get("qc_report", "")
    if isinstance(raw_qc, list):
        text_parts = [part if isinstance(part, str) else part.get("text", "") for part in raw_qc]
        qc_text = "".join(text_parts).upper()
    else:
        qc_text = str(raw_qc).upper()
        
    # Strictly evaluate the pass/fail flag
    if "STATUS: FAILED" in qc_text or "FAILED" in qc_text:
        return {"next": "developer", "qc_report": ""}
        
    if has_run and ("X"in state["execution_output"] or "ERROR" in state["execution_output"].upper()):
        print("Supervisor Alert: Runtime failure caught. Routing back to developer for bug fixing...")
        return {"next": "developer", "execution_output": ""}

    if has_code and has_qc and not has_run:
        return {"next": "executor"}
        
    return {"next": "FINISH"}

# --- EXECUTOR NODE ---
def executor_node(state: AgentState) -> dict:
    """Dynamically executes ANY Python code block generated by the developer.
    Supports persistent desktop GUI apps natively."""
    print("\n[System Action: EXECUTING DYNAMIC RUNNER]")
    
    code_str = state.get("current_code", "").strip()
    
    # 1. Clean markdown formatting backticks if present
    if "```python" in code_str:
        code_str = code_str.split("```python")[1].split("```")[0].strip()
    elif "```" in code_str:
        code_str = code_str.split("```")[1].split("```")[0].strip()

    # 2. Smart Persistent Execution Harness for GUI apps
    # If it's a Tkinter/GUI app, it needs root.mainloop() to remain open for user interaction.
    # We append a classic execution wrapper if it doesn't already have one.
    if "tk.Tk" in code_str or "tkinter" in code_str.lower():
        if "mainloop()" not in code_str:
            print("GUI Application detected. Appending persistent mainloop entrypoint...")
            code_str += "\n\nif __name__ == '__main__':\n    root = tk.Tk()\n    app = Calculator(root)\n    root.mainloop()"
    
    # 3. Handle non-GUI standard naked script functions
    elif not is_executable_script(code_str):
        print("💡 Notice: Only definitions found. Appending automatic self-test invocation...")
        code_str += (
            "\n\n# Automated Dynamic Test Harness\n"
            "import inspect\n"
            "import sys\n"
            "current_module = sys.modules[__name__]\n"
            "functions = inspect.getmembers(current_module, inspect.isfunction)\n"
            "if functions:\n"
            "    name, func = functions[0]\n"
            "    sig = inspect.signature(func)\n"
            "    try:\n"
            "        if len(sig.parameters) == 1:\n"
            "            print(f'Auto-Executing `{name}` with sample input (5):', func(5))\n"
            "        else:\n"
            "            print(f'Auto-Executing `{name}`:', func())\n"
            "    except Exception as e:\n"
            "        print(f'Auto-Execution snippet skipped: {e}')\n"
        )

    # 4. Write code dynamically to an isolated temporary file
    with tempfile.NamedTemporaryFile(suffix=".py", delete=False, mode='w', encoding='utf-8') as temp_file:
        temp_file.write(code_str)
        temp_file_path = temp_file.name

    try:
        print("Launching the application window. Go ahead and interact with it!")
        print("Note: The LangGraph workflow will pause here and finish automatically once you close the Calculator UI window.")
        
        # 5. Run as a blocking subprocess. This holds the terminal open exactly as long 
        # as your calculator window is alive.
        result = subprocess.run(
            [sys.executable, temp_file_path],
            capture_output=True,
            text=True,
            timeout=None  # REMOVED TIMEOUT so the UI stays open indefinitely for the user
        )
        
        if result.returncode == 0:
            output = f"SUCCESSFUL RUN AND USER EXIT:\n{result.stdout}"
        else:
            output = f"RUNTIME ERROR:\n{result.stderr}"
            
    except Exception as e:
        output = f"EXECUTION CRASHED: {str(e)}"
    finally:
        # 6. Clean up temporary filesystem footprint
        try:
            os.remove(temp_file_path)
        except:
            pass

    return {
        "execution_output": output,
        "next": "FINISH"
    }